### ISSUE TITLE
How to re run the importer?

### ISSUE THREAD

**Issue by AlexandruMV** [gisgraphy/gisgraphy#11]
I only imported one country (from geonames) and I whant to add more countries. I can't find any documentation on this.

**Comment by gisgraphy** [comment]
Hi

once done, the importer can not be re run. you have to reset and re run 
via the admin interface

its is a functionnality that could be great but I actually focus on 
relevance of the geocoding and reverse geocoding egine.

any pull request is welcomed :)

**Comment by AlexandruMV** [comment]
thank you but can you provide me the url of the page with the reset function? because the interface look very messed up now after importer was done.

**Comment by gisgraphy** [comment]
Go to the admin UI (/mainMenu.html) log in, ang then Menu Admin=>reset 
import

**Comment by AlexandruMV** [comment]
ok.
