### ISSUE TITLE
I've been trying to import the data on a server, everytime it reaches this step I get the error:

### ISSUE THREAD

**Issue by ilsp** [gisgraphy/gisgraphy#12]
Error : An error occurred when processing GeonamesLanguageimporter on file iso-languagecodes.txt on line 1000 : org.hibernate.exception.ConstrainViolationException: could not insert: [com.gisgraphy.domain.geoloc.entity.Language]
I'm only importing Mexico data files.

**Comment by gisgraphy** [comment]
You've probably run the importer several times, try to reset the import 
via the admin menu/ reset import (/mainMenu.html)
