### ISSUE TITLE
Quattroshapes file retriever - import error

### ISSUE THREAD

**Issue by andrewb-ms** [gisgraphy/gisgraphy#17]
Did a stock installation using Docker image.  Ran import on everything, but got this error:

Quattroshapes file retriever | 0% :0 / 0 (0 left(s)) Error : error retrieving or decompres file : java.io.FileNotFoundException: Sorry, the server return an 404 status code for http://download.gisgraphy.com/import/quattroshapes/shapes.gis, the file probably not exists or the URL is not correct |   |  
-- | -- | -- | --
  |

**Comment by andrewb-ms** [comment]
This is causing the full import to fail

**Comment by gisgraphy** [comment]
The file has been added.Gisgraphy v 5.0 is still in beta and need things to be polished

**Comment by andrewb-ms** [comment]
Thanks - this fixed that issue
