### ISSUE TITLE
Use https for nominatim.openstreetmap.org

### ISSUE THREAD

**Issue by grischard** [gisgraphy/gisgraphy#22]
The nominatim geocoding service at nominatim.openstreetmap.org is available over https, and [will soon start redirecting all http requests to https](https://lists.openstreetmap.org/pipermail/geocoding/2018-January/001918.html).

Would it please be possible to make all nominatim requests over https?

**Comment by gisgraphy** [comment]
Where do you see nominatim calls ? do you mean map tiles url ?

Gisgraphy is an alternative to nominatim, so I find strange to have 
nominatim URL, but tell me and sure I'll do the modifications.

**Comment by grischard** [comment]
Bonjour! I see nominatim here:

https://github.com/gisgraphy/gisgraphy/blob/2641d14cd0b3b725154db4eddb5de7f11e8dcba7/src/site/resources/compare/js/models.js#L85

I also see a few http requests to http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png that will soon result in a redirect to https.

**Comment by gisgraphy** [comment]
Done for tiles and Nominatim. thanks.
