### ISSUE TITLE
Gisgraphy installation problem with Apache Tomcat server

### ISSUE THREAD

**Issue by balajiputhiran** [gisgraphy/gisgraphy#24]
This is my critical problem of installing the Gisgraphy locally. For the past week I am trying to run Gisgraphy web service in my web browser locally but I am not able to configure and run due to lack of reference in Gisgraphy installation. I am trying to install gisgraphy in my Ubuntu Operating system.

Hereby I have mentioned below reference link for which I have followed by the installation of Gisgraphy

http://www.gisgraphy.com/documentation/installation/

Problem:

I installed Gisgraphy in my PC successfully. Even though I started Gisgraphy using this below command successfully, it works fine

    ****ubuntu@ubuntu-in-ws085:~/gisgraphy-5.0-beta1$ ./start.sh** 
    gisgraphy starting ...
    Logs are outptut to ./logs/gisgraphy.log
    Use the stop.sh script (in the same directory) to shutdown
    Ok
    ubuntu@ubuntu-in-ws085:~/gisgraphy-5.0-beta1$** 

But after  `./start.sh` running this command I need to check to see if it really works well. I need to check whether this Gisgraphy will be run in my local server or not but it's not running properly in my local web server.

What should I do? 

I don't know really where it's went wrong in my installation procedure. Can you please anyone of you help me else give me proper documentation for Gisgraphy installation "critical'. 

http://localhost:8080/admin/users.html

http://localhost:8080/mainMenu.html

**Error:

    HTTP Status 404 - /mainMenu.html
    type Status report
    message /mainMenu.html
    description The requested resource is not available.
    Apache Tomcat/7.0.52 (Ubuntu)**

**Comment by gisgraphy** [comment]
A log extract when the server starts will help.

By the way, why do you use tomcat, Gisgraphy already include Jetty that works fine.

**Comment by gisgraphy** [comment]
No news? I close the bug.

**Comment by balajiputhiran** [comment]
I can't understand ? What you are saying exactly Please let me explain elaborately
