### ISSUE TITLE
Most places (POIs) aren't found or are incorrect

### ISSUE THREAD

**Issue by RaphaelFourdrilis** [gisgraphy/gisgraphy#29]
Hello,

I have been playing with the comparer https://www.gisgraphy.com/compare/ and maybe, just maybe, you shouldn't have wrote "We have nothing to hide" ~

I've tried searching for Arc de Triomphe:

![gisgraphy_compare_arcdetriomphe](https://user-images.githubusercontent.com/37067741/38040856-b5358b30-32b0-11e8-9459-6b91403343ee.png)

or even easier, the Eiffel Tower:

![gisgraphy_compare_toureiffel](https://user-images.githubusercontent.com/37067741/38040957-e6d746d8-32b0-11e8-9881-dc3d75e22b6e.png)

Neato!

The funniest one might be Notre Dame de Paris (without specifying the city):

![gisgraphy_compare_notredame](https://user-images.githubusercontent.com/37067741/38041024-0c068324-32b1-11e8-95df-e482b6fa7047.png)

and then when adding the city:

![gisgraphy_compare_notredame2](https://user-images.githubusercontent.com/37067741/38041063-2670866a-32b1-11e8-9119-340611e3a236.png)

Amazing.

Is this something you are aware of ? Your service seems to work for most use cases, but seeing this kind of difference makes me wonder if I should still use Gisgraphy ...

**Comment by gisgraphy** [comment]
it is not a bug, it's a feature :)

the compare page use the geocoding service that accepts addresses. For pois, you have to use the fulltext web service :

 http://services.gisgraphy.com/fulltext/?q=Arc%20de%20Triomphe.
http://services.gisgraphy.com/fulltext/?q=notre%20dame%20de%20paris&style=long&placetype=Religious

documentation is as important as code :-)

I will put a little notice on the compare page and in the documentation, and then close the bug.

just for info, an experimentation is done to have only one web service to search all. the reasons to separate things is that some optimizations are done for addresses (interpolation, house number detection, and more)

**Comment by RaphaelFourdrilis** [comment]
Yeah I finished installing the server locally, and when using the appropriate service, I noticed it works fine :)

But I just found the "Nothing to hide" next to a link, which returns hilarious results, was maybe something to mention :p

But kudos anyhow, and no offense :)
