### ISSUE TITLE
Missing Script

### ISSUE THREAD

**Issue by seubix** [gisgraphy/gisgraphy#34]
Hello,
i did setup GisGraphy by using the provided ./install-wo-docker.sh workflow.
It is now installed in /usr/local/gisgraphy.

I wanted to set up that it starts automaitcly on system start, but
1. the required script startupscript is not there
2. Lokking at the setGisgrapgyAsService.sh i got 2 Questions:
  a.) Should the script not be called  setGisgraphyAsService.sh ? (Typo)
  b.) In the script there it is definied that the Installation my not resist in /usr/local/gisgraphy but your Installation does it like this.. Perhaps the (new) link should be called /usr/local/gisgraphy-latest so the installation can resist wherever...

Thanks
Frank

**Comment by gisgraphy** [comment]
a) yes there is a typo problem. it is now fixed 
b) the files is present in github in src/dist but not included in the dist. I have fix that

Also, those scripts were done very quickly and needs to be tested and improve IMO

**Comment by seubix** [comment]
Hello,
and thanks for your fast work and fix.
I will take the file from github, try and respond the result.
regards
Frank

**Comment by seubix** [comment]
Sorry, but i got more problems with trying to set up gisgraphy to start/stop automaticley.
1. $ cd /usr/local/bin/gisgraphy
    $ ./setGisgrappyAsService.sh
    Result:  Bad substitution.
    Under Ubuntu 16.04 /bin/sh leads to /bin/dash. dash shell does not know ${BASH_SOURCE[0]}.
    So #!/bin/bash -e should be used 

2. Looking inside the ./setGisgraphyAsService.sh the next problem will be that the script will abort because /usr/local/gisgraphy exists (as a directory). Your own installation process installs it there...

3. update-rc.d -f gisgraphy defaults  will not work on modern Linux Systems. They all have moved to systemd and int System does not exist anymore. I am using Ubuntu 16.04 LTS for example.

I can try to work on point 2 but i do not know something about systemd....
Thanks
Frank

**Comment by gisgraphy** [comment]
I don t know systemd but I can learn.

Problem is just lack of time. I currently fix bugs and start to import tiger data from the US.

**Comment by seubix** [comment]
Since yesterday i am trying to learn about systemd but do not understand how it works. I will go further and respond.

**Comment by gisgraphy** [comment]
nothing new, I close the thread
