### ISSUE TITLE
Java API client

### ISSUE THREAD

**Issue by Azbesciak** [gisgraphy/gisgraphy#37]
Hello,
in [readme](https://github.com/gisgraphy/gisgraphy/blob/master/README.md) you are talking about some Java API clients (as same as in [user guide](https://www.gisgraphy.com/documentation/user-guide.php)). However, I couldn't find any jar or maven ref (even through google). Do you provide any separate client, or it is connected with server files? Or in any other way?

**Comment by gisgraphy** [comment]
hi it is obviously clear that it is not a polished part. the java client is in gisgraphy-utils repository : https://github.com/gisgraphy/gisgraphy-utils/tree/master/src/main/java/com/gisgraphy

I don t close the bug since I will make things a little more package and visible.
