### ISSUE TITLE
Geonames alternativeNames.zip file cannot be opened

### ISSUE THREAD

**Issue by ant-tony-antony** [gisgraphy/gisgraphy#39]
I run the importer from my admin panel. I choose alternateNames.zip file to download from GeoNames  server. When the importer trying to download the alternateNames.zip file, it not downloading the entire file and an error occurred when extracting that file. Even i cannot open that file manually. So, how to resolve this issue. These problem leads my importer stops its process. PLease answer me as soon as possible.

This is the error from my importer

`Error : An error occurred when processing GeonamesFeatureSimpleImporter : An error occurred when processing IN.txt : could not insert: [com.gisgraphy.domain.geoloc.entity.AlternateName]; SQL [insert into AlternateName (alternateNameId, countryCode, gisFeature, language, name, preferredName, shortName, source, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [alternatename_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [com.gisgraphy.domain.geoloc.entity.AlternateName]
`
Any answers welcome, Thanks...

**Comment by ant-tony-antony** [comment]
Sorry i didn't check that. But there was file with the size 0000kb inside of that zip. 
Right now i removed the alternateNams.zip from the env.properties file and runing the importer. Let me check how the process is going.
`importer.geonamesFilesToDownload=india.zip` 

And also i have noticed from the importHelper that there are no files exist under the url http\://download.gisgraphy.com/import/openaddresses/ 
How to find these files?

**Comment by gisgraphy** [comment]
hi

let me know.

Iit can (maybe) be a problem with Geonames files on their site.

about the files, you can not list them or download them directly because of a complex process.

**Comment by ant-tony-antony** [comment]
Yes, we cannot download them directly. But getting 404 error when the importer trying to connect the url. 

Will it affect my geocoding process If my server doesn't have openstreetaddress's data?

**Comment by gisgraphy** [comment]
Give me the URL of the alternativeNames file you try to download. why do you mention "openstreetaddress's data" ? alternate names are from Geonames, Not openstreetmap.

**Comment by gisgraphy** [comment]
I get your question but the title say "Geonames alternativeNames.zip" and you talk about open addresses file. it is not the same file. what is writen in the log file when the download fails ? wich URL is mentionned ?
