### ISSUE TITLE
Slow import - Geonames alternate names simple importer

### ISSUE THREAD

**Issue by Azbesciak** [gisgraphy/gisgraphy#40]
I am during data import for Poland through your docker image. However, although note *30 days if you import all the datasets of all countries*, my import already took about 17 hours when the progress of `geonames alternate names` import is in 6%.  And, actually, 6 hours ago it was 5%. My VM has 4 cores, 60gb disc space and 8gb RAM. Also, my host machine OS is Windows 10.

**Comment by gisgraphy** [comment]
Yes I know that it is a long process, if you use SSD or NVME hard drive 
it should be faster

**Comment by gisgraphy** [comment]
we know that import data takes time. if someone has a solution to speed up thing, we are also interested ;-)
