### ISSUE TITLE
Install and configure issue

### ISSUE THREAD

**Issue by magudash** [gisgraphy/gisgraphy#41]
Hi This Magudash
Have a Lunch Gisgrabhy fix the error But i was configured our PostgreSQl password "mdppostgres"
As on installation required as 8.3 but now available only higher version only how can i install due to following issue 

D:\gisgraphy-5.0-beta3>java -Dfile.encoding=UTF-8 -Xmx4G -Xms512m -jar start.jar
2018-09-10 16:58:40.656::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
2018-09-10 16:58:40.734::INFO:  jetty-6.1.3
2018-09-10 16:58:41.312::INFO:  Initializing Spring root WebApplicationContext
WARN [main] JDBCExceptionReporter | SQL Error: 0, SQLState: null
ERROR [main] JDBCExceptionReporter | Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
WARN [main] SettingsFactory | Could not obtain connection to query metadata
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)

Thank and regards Magudash

**Comment by gisgraphy** [comment]
You can change the postgres configuration in the 
webapp/ROOT/WEB-INF/classes/env.properties file

first check that you can connect to postgres on the command line

**Comment by magudash** [comment]
Dear sir
windows server 2016 and PostgreSQL 10.5 and java version 8 also installed
command line postgres aslo run as use well. 
our system command log kindly check


[Error.txt](https://github.com/gisgraphy/gisgraphy/files/2378048/Error.txt)

**Comment by gisgraphy** [comment]
it is not a software problem but a configuration one. please put in the webapp/ROOT/WEB-INF/classes/env.properties file, the ip, login and password of your PostgreSQL server.
