### ISSUE TITLE
How to import some data after some imports has been done?

### ISSUE THREAD

**Issue by ant-tony-antony** [gisgraphy/gisgraphy#42]
I have imported all the required data from the sources(geonames, openstreetmap and quattroshapes **exclude openaddresses** data) for the country INDIA. I run the server everything is perfect. Now i want to import openaddresses data for the same country INDIA. How to import it?. Should i reset all the imported data before to import openaddresses data or is it possible to import without resetting that?

NOTE: Data imported through admin importer.

**Comment by gisgraphy** [comment]
You have to comment the several importer that you have already done in 
/WEB-INF/classes/applicationcontext-geoloc.xml
restart gisgraphy.
go to the admin menu->reset import->mark importer as not done
restart the import.
