### ISSUE TITLE
Crash during import process

### ISSUE THREAD

**Issue by noizde** [gisgraphy/gisgraphy#43]
Hello! We're currently running Gisgraphy 5.0 via a Docker image, and we've been having trouble with importing data for the Philippines.

We're supplying a configuration that specifies `PH.gis` for the files to download, and selecting `Philippines` as the country to download data for in the import dialog. One thing to note is that we have `import.openaddressesFilesToDownload` set to `false` because OpenAddresses has no Philippine coverage. We're able to actually start the import process and the import status shows it progressing and processing files, but this eventually crashes with no informative messages logged.

The only message that indicates anything going wrong is repeated attempts to download `PH.gis` from openaddresses:

`[ERROR] [com.gisgraphy.importer.ImporterHelper] [02 Oct 2018 07:56:45,470] (btpool0-6,) : Can not determine HTTP file size of http://download.gisgraphy.com/import/openaddresses/PH.gis because it does not exists (404)`

Is this something that could cause the import process to fail, or is it likely to be something else?

I've attached the process log for reference:
[gisgraphy.log](https://github.com/gisgraphy/gisgraphy/files/2437172/gisgraphy.log)

**Comment by gisgraphy** [comment]
hi 

you try something more difficult than it should be.

Simply go to the admin menu, and select the options (your countries, the datasets, ..) everything will be fine.

**Comment by noizde** [comment]
Using only the regular provided configuration, I'm now using only the admin menu to specify the options, with dataset as everything *except* OpenAdresses, and the Philippines as the only country to import. The process still crashed shortly after. The log contains:

`[ERROR] [com.gisgraphy.importer.ImporterHelper] [03 Oct 2018 07:30:47,014] (btpool0-7,) : Can not determine HTTP file size of http://download.gisgraphy.com/import/openaddresses/PH.gis because it does not exists (404)`

It looks like it's still attempting to download from OpenAddresses, even if it's set not to import the OpenAddresses dataset. Is this expected behavior?

**Comment by gisgraphy** [comment]
hi I have checked and thefiles doesn't exists for openaddresses , simply unchecked openaddresses importer in the config admin menu. I have check on a local installation and it got an error in the log (logically because the files doesn't exists) but it doesn't crash
