### ISSUE TITLE
Place and Street Editor

### ISSUE THREAD

**Issue by sm2x** [gisgraphy/gisgraphy#45]
Hi,  the editor that is based on Google Maps API V2 is no longer available on Google, are you planning to fix the editor to work on Google Maps API V3?

Also, is there a way to change the editor to use OpenStreetMap instead of Google's, please?

**Comment by davidmascletpro** [comment]
hi it is fix in d847566e8a1afdde75be17e3d084fa2ff0107986, simply replace the files, and it should work :)

**Comment by gisgraphy** [comment]
It is fix in d847566, simply replace the files, and it should work :)

**Comment by sm2x** [comment]
sorry, i'm new to gisgraphy, how do you compile and apply the fixes?
