### ISSUE TITLE
Invalid maximum heap size: -Xmx4G

### ISSUE THREAD

**Issue by kaustubhlohiya** [gisgraphy/gisgraphy#5]
Followed all the steps and getting the above. Kindly Help.
 
I am running Ubuntu 14.04 32 bit with  4 GB RAM and 1 TB HDD.

**Comment by gisgraphy** [comment]
It is not a bug. 4GB is the memory that is necesary when you import all the countries. You can decrease the value it if it is not the case or increase your server memory if it is.
