### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by charleston10** [gisgraphy/gisgraphy#6]
I need create map in my application using this API
Exist some  native map similar the google maps android? [see more](https://developers.google.com/maps/documentation/android-api)

**Comment by gisgraphy** [comment]
There is an android apk that you will find on the gisgraphy website.

**Comment by charleston10** [comment]
I do test apk (dowloaded in play store) but the maps not worked (tested in devices KitKat, Lolipop and Marshmallow)

[image attached - link](https://s32.postimg.org/dqgk4d0s5/Screenshot_2016_07_21_09_51_51.png)
