### ISSUE TITLE
There is a MAJOR issue with the *_featureid_key for unique featureid contraint

### ISSUE THREAD

**Issue by miniatarule** [gisgraphy/gisgraphy#68]
HI! I'm trying to import Canada data to try your application and test the accuracy of the data. On your website the sources where the data are imported the accuracy is not GOOD AT ALL. I want to test a up to date data to see if there is a difference.

I've been trying for days on Linux and Windows and I always get the same problem.

All default parameters are enable and Only Canada is selected as the country.
IT CAN STOP AT  any time when trying to update the data with geonames.

it's look like there is a problem with the  undersea_featureid_key for unique featureid contraint and that is valid for all tables where this constraint is present  (TABLENAME__featureid_key  for unique featureid )

It's really frustrating...I would like to test the application and data but I cannot complete any import.
I read some reported issue....this is look the MAIN ISSUE with your project... Import is not easy.

It's will be nice to be able to resume aborded task and also use existing download files to save some time.
You could do a check to see if a file exist before you download it, a option to use existing download file could be useful also.

It's always stop there if it got there:

Geonames feature simple importer
1000 / 314216 (313216 left(s))
Error : An error occurred when processing GeonamesFeatureSimpleImporter : An error occurred when processing CA.txt : Could not execute JDBC batch update; SQL [insert into UnderSea (adm, adm1Code, adm1Name, adm2Code, adm2Name, adm3Code, adm3Name, adm4Code, adm4Name, adm5Code, adm5Name, adminCentreLocation, amenity, asciiName, cityConfident, cityId, countryCode, elevation, featureClass, featureCode, featureId, fullyQualifiedName, gtopo30, isIn, isInAdm, isInPlace, label, labelPostal, location, modificationDate, name, openstreetmapId, population, shape, source, timezone, zipCode, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [undersea_featureid_key]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update

If you need more information, please let me know.

Thank you in advance for your help!

**Comment by gisgraphy** [comment]
There is no problem with the key, you simply try to import and there is already data in database. Resuming an import is not possible yet. It requires time to do it. And it can not be done in a day.

**Comment by gisgraphy** [comment]
Not a bug
