### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by anakin59490** [gisgraphy/gisgraphy#7]
Hi,
can I use your api/web services for my commercial web application ?
Thank you in advance
Regards
Jérôme

**Comment by gisgraphy** [comment]
Hi

Yes sure. You can subscribe on https://premium.gisgraphy.com. You can test the relevance on services.gisgraphy.com. 

Let me know if questions

Best regards
David


Sent from my mobile

<div>-------- Message d'origine --------</div><div>De : anakin59490 <notifications@github.com> </div><div>Date :10/08/2016  13:56  (GMT+01:00) </div><div>À : gisgraphy/gisgraphy <gisgraphy@noreply.github.com> </div><div>Objet : [gisgraphy/gisgraphy] Commercial use (#7) </div><div>
</div>Hi,
can I use your api/web services for my commercial web application ?
Thank you in advance
Regards
Jérôme

**Comment by anakin59490** [comment]
So, for a commercial use, i can either download and install by my-self your
program and database for free or pay for your premium Web services without
installation.
Is it right ?

Regards,
Jérôme

Le 10 août 2016 14:21, "gisgraphy" <notifications@github.com> a écrit :

Hi

Yes sure. You can subscribe on https://premium.gisgraphy.com. You can test
the relevance on services.gisgraphy.com.

Let me know if questions

Best regards
David


Sent from my mobile

<div>-------- Message d'origine --------</div><div>De : anakin59490 <
notifications@github.com> </div><div>Date :10/08/2016 13:56 (GMT+01:00)
</div><div>À : gisgraphy/gisgraphy <gisgraphy@noreply.github.com>
</div><div>Objet : [gisgraphy/gisgraphy] Commercial use (#7) </div><div>
</div>Hi,
can I use your api/web services for my commercial web application ?
Thank you in advance
Regards
Jérôme

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gisgraphy/gisgraphy/issues/7#issuecomment-238850094>,
or mute the thread

**Comment by gisgraphy** [comment]
that's right except that you can not install gisgraphy due to a recent 
hacking https://github.com/gisgraphy/gisgraphy/issues/3
