### ISSUE TITLE
Issue in GisgraphyImporter: An error occurred when processing GeonamesCountryImporter : An error occurred when processing countryInfo.txt 

### ISSUE THREAD

**Issue by ChWasiUllah** [gisgraphy/gisgraphy#76]
I tried to install 3 times Gisgraphy and found the following error

**Error : An error occurred when processing GeonamesCountryImporter : An error occurred when processing countryInfo.txt : An Error occurred on Line 101 for ID IDN 360 ID Indonesia Jakarta 1919440 242968342 AS .id IDR Rupiah 62 ##### ^(\d{5})$ id,en,nl,jv 1643084 PG,TL,MY : a different object with the same identifier value was already associated with the session: [com.gisgraphy.domain.geoloc.entity.Country#108]; nested exception is org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [com.gisgraphy.domain.geoloc.entity.Country#108]**

Can anyone help how to fix it ?

**Comment by gisgraphy** [comment]
it is known, I have put a snapshot on http://download.gisgraphy.com/snapshots/ with the fix.
